-- Marketing tab rebuild: campaigns become a guided workflow.
--
-- marketing_campaigns already carried name/status/notes/metrics/dates and
-- (schema_070) client_id — that stays the assignment: a campaign hangs off
-- a crm_clients row, or off NULL, which means the account's own business
-- ("Made by MARQ"). No second client list.
--
-- answers   — one entry per builder step, keyed by step id:
--             { choice?, custom?, data?, ai_summary?, prefilled?, done_at? }
-- current_step / skip_gating — the step the user is on, and the escape
--             hatch from sequential gating once they know the flow.
-- plan_md   — the assembled campaign plan (markdown), written at review.
-- results   — manual results: { what_ran, spend, leads, calls, closes, revenue }
-- results_source — who fills results: manual | internal_dialing (read
--             straight from call_outcomes/leads) | external (future
--             platform connectors populate the same shape).
alter table marketing_campaigns
  add column if not exists answers jsonb not null default '{}'::jsonb,
  add column if not exists current_step int not null default 1,
  add column if not exists skip_gating boolean not null default false,
  add column if not exists plan_md text,
  add column if not exists launched_at timestamptz,
  add column if not exists last_activity_at timestamptz not null default now(),
  add column if not exists results jsonb not null default '{}'::jsonb,
  add column if not exists results_source text not null default 'manual'
    check (results_source in ('manual', 'internal_dialing', 'external')),
  add column if not exists target_metric text,
  add column if not exists target_value numeric,
  add column if not exists budget_amount numeric,
  add column if not exists budget_period text;

-- Assets are GENERATED by the builder's step 6 and belong to a campaign.
-- The rows that already existed were made by hand and already exist as
-- things, so they start as done.
alter table marketing_assets
  add column if not exists campaign_id uuid references marketing_campaigns(id) on delete cascade,
  add column if not exists status text not null default 'needed'
    check (status in ('needed', 'in_progress', 'done'));
update marketing_assets set status = 'done' where campaign_id is null and status = 'needed';

create index if not exists marketing_assets_campaign_id_idx on marketing_assets(campaign_id);
create index if not exists marketing_campaigns_client_id_idx on marketing_campaigns(client_id);
