-- Mastermind by MARQ — Phase 47 schema (invoice list/detail/void). Run
-- once, after schema_046_client_media.sql, in the Supabase SQL editor.
-- Purely additive — two new nullable/defaulted columns on the existing
-- client_invoices table, no existing row touched beyond gaining them.
-- Safe to re-run in full.

-- A short, stable, human-readable label for the list/detail views —
-- generated once at insert time, independent of id/created_at ordering
-- so it never changes even if a row is edited.
alter table client_invoices add column if not exists invoice_number bigint generated by default as identity;

-- Required reason text for the Void action — distinct from a re-opened
-- draft (see worker/handlers/client-crm.ts::voidClientInvoice), which
-- clears status back to 'draft' instead of setting this.
alter table client_invoices add column if not exists void_reason text;
